### ISSUE TITLE
 The dependency safety_gym can't be found!

### ISSUE THREAD

**Issue by hdadong** [yardenas/la-mbda#4] opened 2023-01-14 15:54 UTC
Hi! it seens the dependency: " safety_gym @ https://github.com/yardenas/safety-gym/tarball/dm_hack' "  can't be found!
what is the different between the safety-gym you used and the primal  safety-gym?
Thanks!

**Comment by yardenas** [comment] 2023-01-14 16:34
Hi @hdadong!
Can you write here the exact error message you get?

Running `pip install .` works on my end, so not sure what exactly the issue is. Also,  https://github.com/yardenas/safety-gym/tarball/dm_hack seems to download the tarball. 

You can view the code [here](https://github.com/yardenas/safety-gym/tree/dm_hack) and `git diff` against [`master`](https://github.com/yardenas/safety-gym/tree/master) branch. The main difference is running deepmind-control as backend, instead of mujoco-py (more details [here](https://github.com/yardenas/safety-gym/blob/e7d0209d253bdf80469b62e2eba06e34c9bc1cf9/safety_gym/envs/world.py#L76)). I didn't observe any differences in results by using deepmind-control, the only difference was not being able to render correctly on cluster compute while using mujoco-py (which is crucial for LAMBDA).

Let me know if that answers your question. In any case, I'm happy to help with the tarball issue.

**Comment by yardenas** [comment] 2023-01-20 13:56
Closing this for now, feel free to reopen if the issue persists

**Closed as completed** 2023-01-20 13:56 UTC
